### ISSUE TITLE
Possible addition of image/tiff

### ISSUE THREAD

**Issue by psander-com** [DinoChiesa/Apigee-Java-XOP-Handler#1]
Hi Dino,

thanks for this usefull apigee lib. It is possible to a `image/tiff` too?

Kind regards

**Comment by DinoChiesa** [comment]
Yes of course, I can add `image/tiff` as a "by default" acceptable ctype for the 2nd part, the embedded/attached document. But, you can support image/tiff right now just using the appropriate `part2-ctypes` setting: 
```
<JavaCallout name='Java-ProcessXop-2'>
  <Properties>
    <Property name="source">message</Property>
    <Property name="action">transform_to_embedded</Property>
    <!-- allow either png or tiff -->
    <Property name="part2-ctypes">image/tiff, image/png</Property>
  </Properties>
  <ClassName>com.google.apigee.edgecallouts.XopHandler</ClassName>
  <ResourceURL>java://apigee-custom-xop-handler-20220706.jar</ResourceURL>
</JavaCallout>
```

**Comment by psander-com** [comment]
Thanks alot, i didn't recognize the properties for the callout. Thanks for your support at apigee. Kind regards
